name: KingMineRandCustomizer
version: '${project.version}'
main: de.Kingmine.randcustomizer.KingMineRandCustomizer
api-version: '1.20'
description: This is the Plugin for Kingmine Citybuild Server.
authors:
  - Terrocraft
  - Schemil053
depend:
  - PlotSquared
  - WorldEdit
commands:
  randeditmode:
    permission: randcustomizer.randeditmode