name: RandCustomizer
version: '${project.version}'
main: de.terrocraft.randcustomizer.RandCustomizer
api-version: '1.20'
description: This is the Plugin for Kingmine Citybuild Server.
authors:
  - Terrocraft
  - Schemil053
  - LevinGamer8
depend:
  - PlotSquared
  - WorldEdit
commands:
  randeditmode:
    permission: randcustomizer.randeditmode