name: RandCustomizer
version: '${project.version}'
main: de.emilschlampp.randcustomizer.RandCustomizer
api-version: '1.20'
depend:
  - PlotSquared
  - WorldEdit
commands:
  randeditmode:
    permission: randcustomizer.randeditmode